# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4ANCIgGb_Kq-IKD9VuFQn5Y1YbXWDhW
"""

#  Write a program that takes an integer input from the user and checks whether the number is odd or even
a=int(input('enter a number:'))
if(a%2==0):
  print('even')
else:
  print('odd')

#  Write a program to check if a given year is a leap year. A leap year is divisible by 4 but not by 100
#  unless it is also divisible by 400.

a = int(input("enter a year:"))
if(a%4==0 or a%400==0):
  print("leap year")
else:
  print("not a leap year ")

# Write a program that takes a percentage (integer) as input and prints the corresponding grade based
# on the following criteria:
# >= 90: Grade A
# # >= 80: Grade B
# >= 70: Grade C
# >= 60: Grade D
# < 60: Grade F

a = int(input("enter percentage:"))
if(a>=90):
   print("Grade A")
elif(a>=80):
     print("Grade B")
elif(a>=70):
      print("Grade C")
elif(a>=60):
      print("Grade D")
else:
      print("Grade F")

# Write a program that checks if a given letter is a vowel (a, e, i, o, u) or a consonant.

a = input("enter a letter:")
if(a in ('a','e','i','0','u')):
  print("vowel")
else:
  print("consonant")

#  Write a program that takes a number as input and checks whether it is positive, negative, or zero.

a = int(input("enter a number:"))
if(a>0):
  print("positive")
elif(a<0):
  print("negative")
else:
  print("zero")

#  Write a program that takes three numbers as input and prints the largest of the three.

a=int(input("enter a number:"))
b=int(input("enter a number:"))
c=int(input("enter a number:"))
if(a>b and a>c):
  print(a)
elif(b>a and b>c):
  print(b)
else:
  print(c)

#  Write a program that checks if a username and password entered by the user match the pre-set values
#  username = "admin" and password = "1234". If both match, print "Login Successful", otherwise print
#  "Login Failed".

a = input("username:")
b = int(input("password:"))
if(a== 'admin' and b==1234):
  print("Login successful")
else:
  print("Login Failed")

#  Write a program that calculates the Body Mass Index (BMI) based on user input for weight (in
#  kilograms) and height (in meters). Then categorize the BMI into:
#  Underweight (BMI < 18.5)
#  Normal weight (18.5 <= BMI < 24.9)
#  Overweight (25 <= BMI < 29.9)
#  Obesity (BMI >= 30)
#  Use the formula: BMI = weight / (height ** 2)

a = float(input("enter your height"))
b = int(input("enter your weight:"))
BMI = b/a**2
if(BMI<18.5):
  print("Underweight")
elif(18.5<=BMI<24.9):
  print("Normal weight")
elif(25<=BMI<29.9):
  print("Overweight")
else:
  print("Obesity")

#  Write a program that categorizes a given age into different groups:
#  Infant (0-1 year)
#  Toddler (2-4 years)
#  Child (5-12 years)
#  Teenager (13-19 years)
#  Adult (20-59 years)
#  Senior (60 years and above)

a = 60
if(0<=a<=1):
  print('Infant')
elif(2<=a<=4):
  print('Toddler')
elif(5<=a<=12):
  print('child')
elif(13<=a<=19):
  print('Teenager')
elif(20<=a<=59):
  print('Adult')
else:
  print('senior')

#  Write a program that takes an integer (1-7) as input and prints the corresponding day of the week (1
#  for Monday, 2 for Tuesday, etc.).

a = int(input('enter a number:'))
if(a==7):
  print('sunday')
elif(a==1):
  print('monday')
elif(a==2):
  print('tuesday')
elif(a==3):
  print('wednesday')
elif(a==4):
  print('thursday')
elif(a==5):
  print('friday')
elif(a==6):
  print('saturday')

#  Write a program that takes the name of a month as input and prints the number of days in that
#  month. Consider leap years for February.

a = input('name of month:')
if(a in ('january','march','may','july','august','october','december')):
  print('31 days')
elif(a in ('april','june','september','november')):
  print('30 days')
else:
  print('28,29 days')

